version: '2'

services:
  jaeger-query:
    image: jaegertracing/jaeger-query
    #command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
    command: ["--span-storage.type=elasticsearch", "--es.server-urls=http://elasticsearch:9200"]
    ports:
      - "16686:16686"
      - "16687"
    restart: on-failure
    networks:
      - storage_network

networks:
  storage_network:
    external: true
