version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pypi-server
      POSTGRES_USER: pypi-server
      POSTGRES_DB: pypi-server
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - jaeger-collector_datacenter_a_network
      - jaeger-collector_datacenter_b_network

  pypi_server:
    image: mosquito/pypi-server:latest
    links:
      - db
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./packages:/usr/lib/pypi-server
    networks:
      - jaeger-collector_datacenter_a_network
      - jaeger-collector_datacenter_b_network
    environment:
      # Database URL. Use `sqlite3:///` or `mysql://` when needed
      DB: "postgres://pypi-server:pypi-server@db/pypi-server"

networks:
  jaeger-collector_datacenter_a_network:
    external: true
  jaeger-collector_datacenter_b_network:
    external: true
