version: '3.5'

# 3 node cluster
# If you see exit code 137 (OOM killer) then ensure Docker has access to more resources
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - storage_network

#  kibana:
#    image: docker.elastic.co/kibana/kibana:6.3.2
#    ports:
#      - "5601:5601"
#
#    networks:
#      - storage_network

networks:
  storage_network:
    name: storage_network
