version: '3'

services:
  web:
    build:
      context: ../../
      dockerfile: etc/app/Dockerfile

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../.:/code
    ports:
      - "8000:8000"
    networks:
      - jaeger-collector_datacenter_a_network
    environment:
      - JAEGER_AGENT_HOST=jaeger-agent

networks:
  jaeger-collector_datacenter_a_network:
    external: true
