version: '3'

services:
  nginx:
    image: nginx:latest
    links:
      - uwsgi
    ports:
      - "8000:8080"
    networks:
      - app_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  uwsgi:
    restart: always
    build:
      context: ../../.
      dockerfile: etc/app/Dockerfile
    container_name: django_with_jaeger_a
    networks:
      - app_network
    volumes:
      - "../../.:/opt/django/"
      - "../../etc/app/uwsgi.ini:/etc/uwsgi.ini"

#  web_b:
#    image: django_app-baseimage
#
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ../../.:/code
#    ports:
#      - "8001:8000"
#    networks:
#      - jaeger-collector_datacenter_b_network
#    environment:
#      - JAEGER_AGENT_HOST=jaeger-agent_b

networks:
  app_network:
    external: true
