version: '3'

services:
  _base_image:
    build:
      context: ../../
      dockerfile: etc/app/Dockerfile
    image: django_app-baseimage
    entrypoint: ""
    command: /bin/false

  web:
    image: django_app-baseimage

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../.:/code
    ports:
      - "8000:8000"
    networks:
      - jaeger-collector_datacenter_a_network
    environment:
      - JAEGER_AGENT_HOST=jaeger-agent

  web_b:
    image: django_app-baseimage

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../.:/code
    ports:
      - "8001:8000"
    networks:
      - jaeger-collector_datacenter_b_network
    environment:
      - JAEGER_AGENT_HOST=jaeger-agent_b

networks:
  jaeger-collector_datacenter_a_network:
    external: true
  jaeger-collector_datacenter_b_network:
    external: true
