version: '3.5'

services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector
    # cassandra command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
    # elasticsearch
    command: ["--span-storage.type=elasticsearch", "--es.server-urls=http://elasticsearch:9200"]
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250"
      - "9411:9411"
    restart: on-failure
    networks:
#      - cassandra_common_network
      - storage_network
      - app_network

#  jaeger-collector_b:
#    image: jaegertracing/jaeger-collector
#    command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
#    ports:
#      - "14269"
#      - "14269:14268"
#      - "14267"
#      - "14250"
#      - "9412:9411"
#    restart: on-failure
#    networks:
#      - cassandra_common_network
#      - elasticsearch_common_network
#      - datacenter_b_network


networks:
  storage_network:
    external: true

  app_network:
    name: app_network
