version: "3.5"
services:
  prom:
    image: quay.io/prometheus/prometheus:v2.0.0
    volumes:
     - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - 9090:9090
    depends_on:
     - exporter
    networks:
      - storage_network
      - app_network
  exporter:
    image: prom/node-exporter:latest
    ports:
     - "9100:9100"
    networks:
      - storage_network
      - app_network
#    network_mode: host
  grafana:
    image: grafana/grafana
    ports:
     - "3000:3000"
    depends_on:
      - prom

    networks:
      - storage_network
      - app_network




networks:
  storage_network:
    external: true

  app_network:
    name: app_network
